### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by kdc1143** [ivanwhaf/xxqg-helper#10]
首先感谢作者的无私奉献和持续更新

提一点优化建议，在学习文章之前，可以打开广播电台，这样学习文章的时间中系统会同时积累视频/音频学习时间，从而可以大幅度减少视频学习的时间，提高总体刷分效率

**Comment by ivanwhaf** [comment]
已经在按这个思路改了，你方便进个群吧



---原始邮件---
发件人: "kdc1143"<notifications@github.com&gt;
发送时间: 2019年11月5日(星期二) 下午4:27
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ivanwhaf/xxqg-helper] 优化建议 (#10)



首先感谢作者的无私奉献和持续更新
 
提一点优化建议，在学习文章之前，可以打开广播电台，这样学习文章的时间中系统会同时积累视频/音频学习时间，从而可以大幅度减少视频学习的时间，提高总体刷分效率

**Comment by 85524365** [comment]
> 已经在按这个思路改了，你方便进个群吧
> […](#)
> ---原始邮件--- 发件人: "kdc1143"<notifications@github.com&gt; 发送时间: 2019年11月5日(星期二) 下午4:27 收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [ivanwhaf/xxqg-helper] 优化建议 (#10) 首先感谢作者的无私奉献和持续更新 提一点优化建议，在学习文章之前，可以打开广播电台，这样学习文章的时间中系统会同时积累视频/音频学习时间，从而可以大幅度减少视频学习的时间，提高总体刷分效率 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大神，怎么进群呀？

**Comment by ivanwhaf** [comment]
916407903



---原始邮件---
发件人: "85524365"<notifications@github.com&gt;
发送时间: 2019年11月12日(星期二) 中午12:43
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Ivan"<874869814@qq.com&gt;;
主题: Re: [ivanwhaf/xxqg-helper] 优化建议 (#10)


 
已经在按这个思路改了，你方便进个群吧
 …
 ---原始邮件--- 发件人: "kdc1143"<notifications@github.com&gt; 发送时间: 2019年11月5日(星期二) 下午4:27 收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [ivanwhaf/xxqg-helper] 优化建议 (#10) 首先感谢作者的无私奉献和持续更新 提一点优化建议，在学习文章之前，可以打开广播电台，这样学习文章的时间中系统会同时积累视频/音频学习时间，从而可以大幅度减少视频学习的时间，提高总体刷分效率 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
大神，怎么进群呀？
