### ISSUE TITLE
变得更方便的一些小建议

### ISSUE THREAD

**Issue by seseshenqiu** [ivanwhaf/xxqg-helper#7]
1.希望文章任务由“要闻”变成“订阅”
我自己改了，但是在订阅页面一直往下拉，不会进入文章里边；
订阅里边每天更新很丰富，不会出现几天不更新的尴尬局面。

2.希望视频任务由“新闻联播”变成“百灵”短视频
百灵点开第一个，会自动播放下一个，直接设置播放18分钟，时长、个数一般就够了。

3.希望分享和收藏能够融合到文章任务里边
阅读下一篇文章前，自动分享和收藏

4、希望增加一个评论任务
只需要几个固定的语句，评论之后自动删除，不留痕迹，该功能可以和收藏分享放一块。

总之谢谢大神的这款神器。
好人一生平安

**Comment by seseshenqiu** [comment]
5.视频任务改成电台里边的音乐
这样后台听着音乐，前台刷着文章，速度会大大提高

6.每篇文章的时长建议随机
例如可以设置为110——120秒之间随机时长，可以有效应对检测屏蔽

**Comment by ivanwhaf** [comment]
谢谢建议，你这些建议其实我自己用的时候都考虑过，我传的是通用的版本，要闻是折中的办法，😂我自己的版本是学习自己订阅的栏目，可以保证每天6个新闻要闻不能每天都出6个新闻。可以根据自己的需要修改。总之谢谢你了，我有空会更新，最近要复习考试



---原始邮件---
发件人: "瑟瑟深秋"<notifications@github.com&gt;
发送时间: 2019年10月26日(星期六) 晚上6:49
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ivanwhaf/xxqg-helper] 变得更方便的一些小建议 (#7)



1.希望文章任务由“要闻”变成“订阅”
 我自己改了，但是在订阅页面一直往下拉，不会进入文章里边；
 订阅里边每天更新很丰富，不会出现几天不更新的尴尬局面。
 
2.希望视频任务由“新闻联播”变成“百灵”短视频
 百灵点开第一个，会自动播放下一个，直接设置播放18分钟，时长、个数一般就够了。
 
3.希望分享和收藏能够融合到文章任务里边
 阅读下一篇文章前，自动分享和收藏
 
4、希望增加一个评论任务
 只需要几个固定的语句，评论之后自动删除，不留痕迹，该功能可以和收藏分享放一块。
 
总之谢谢大神的这款神器。
 好人一生平安

**Comment by ivanwhaf** [comment]
对了我之所以分享收藏分开来是为了开源代码好理解，我传的版本完全是为了方便自定义修改，自己用的代码就是按你说的那样的



---原始邮件---
发件人: "瑟瑟深秋"<notifications@github.com&gt;
发送时间: 2019年10月26日(星期六) 晚上6:49
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ivanwhaf/xxqg-helper] 变得更方便的一些小建议 (#7)



1.希望文章任务由“要闻”变成“订阅”
 我自己改了，但是在订阅页面一直往下拉，不会进入文章里边；
 订阅里边每天更新很丰富，不会出现几天不更新的尴尬局面。
 
2.希望视频任务由“新闻联播”变成“百灵”短视频
 百灵点开第一个，会自动播放下一个，直接设置播放18分钟，时长、个数一般就够了。
 
3.希望分享和收藏能够融合到文章任务里边
 阅读下一篇文章前，自动分享和收藏
 
4、希望增加一个评论任务
 只需要几个固定的语句，评论之后自动删除，不留痕迹，该功能可以和收藏分享放一块。
 
总之谢谢大神的这款神器。
 好人一生平安

**Comment by ivanwhaf** [comment]
音乐的话我一开始试过，包括广播和电台，但是好像不能重复计分，今天听过同一个明天再听就不加分了。至于随机时间应该不要紧，用的这么多人从来没出过问题没有被封过，倒是我同学用python写的模拟登录的被封过，这个模拟控件操作的应该查不出来

---原始邮件---
发件人: "瑟瑟深秋"<notifications@github.com&gt;
发送时间: 2019年10月26日(星期六) 晚上6:56
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [ivanwhaf/xxqg-helper] 变得更方便的一些小建议 (#7)



5.视频任务改成电台里边的音乐
 这样后台听着音乐，前台刷着文章，速度会大大提高
 
6.每篇文章的时长建议随机
 例如可以设置为110——120秒之间随机时长，可以有效应对检测屏蔽

**Comment by seseshenqiu** [comment]
> 谢谢建议，你这些建议其实我自己用的时候都考虑过，我传的是通用的版本，要闻是折中的办法，我自己的版本是学习自己订阅的栏目，可以保证每天6个新闻要闻不能每天都出6个新闻。可以根据自己的需要修改。总之谢谢你了，我有空会更新，最近要复习考试
> […](#)
> ---原始邮件--- 发件人: "瑟瑟深秋"<notifications@github.com&gt; 发送时间: 2019年10月26日(星期六) 晚上6:49 收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [ivanwhaf/xxqg-helper] 变得更方便的一些小建议 (#7) 1.希望文章任务由“要闻”变成“订阅” 我自己改了，但是在订阅页面一直往下拉，不会进入文章里边； 订阅里边每天更新很丰富，不会出现几天不更新的尴尬局面。 2.希望视频任务由“新闻联播”变成“百灵”短视频 百灵点开第一个，会自动播放下一个，直接设置播放18分钟，时长、个数一般就够了。 3.希望分享和收藏能够融合到文章任务里边 阅读下一篇文章前，自动分享和收藏 4、希望增加一个评论任务 只需要几个固定的语句，评论之后自动删除，不留痕迹，该功能可以和收藏分享放一块。 总之谢谢大神的这款神器。 好人一生平安 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可否分享一下，阅读订阅文章的代码，我在通用版上修改了要闻为订阅，结果在订阅页面一直下拉

**Comment by ivanwhaf** [comment]
那个暂时还没法解决，因为是根据新闻底下的小类别点击的，比如“学习强国学习平台”。换个大类别小类别不一样了。autojs的api不是很完善，导致我要依次从上到下点击列表框中的新闻元素点不了，只能根据底下的小文字一个个点。api里面有一个降序排序函数有问题，当时踩坑试了好久没解决



---原始邮件---
发件人: "瑟瑟深秋"<notifications@github.com&gt;
发送时间: 2019年10月29日(星期二) 上午10:09
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Ivan"<874869814@qq.com&gt;;
主题: Re: [ivanwhaf/xxqg-helper] 变得更方便的一些小建议 (#7)


 
谢谢建议，你这些建议其实我自己用的时候都考虑过，我传的是通用的版本，要闻是折中的办法，我自己的版本是学习自己订阅的栏目，可以保证每天6个新闻要闻不能每天都出6个新闻。可以根据自己的需要修改。总之谢谢你了，我有空会更新，最近要复习考试
 …
 ---原始邮件--- 发件人: "瑟瑟深秋"<notifications@github.com&gt; 发送时间: 2019年10月26日(星期六) 晚上6:49 收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [ivanwhaf/xxqg-helper] 变得更方便的一些小建议 (#7) 1.希望文章任务由“要闻”变成“订阅” 我自己改了，但是在订阅页面一直往下拉，不会进入文章里边； 订阅里边每天更新很丰富，不会出现几天不更新的尴尬局面。 2.希望视频任务由“新闻联播”变成“百灵”短视频 百灵点开第一个，会自动播放下一个，直接设置播放18分钟，时长、个数一般就够了。 3.希望分享和收藏能够融合到文章任务里边 阅读下一篇文章前，自动分享和收藏 4、希望增加一个评论任务 只需要几个固定的语句，评论之后自动删除，不留痕迹，该功能可以和收藏分享放一块。 总之谢谢大神的这款神器。 好人一生平安 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可否分享一下，阅读订阅文章的代码，我在通用版上修改了要闻为订阅，结果在订阅页面一直下拉
